version: "3.8" # Specify the version of Docker Compose

# Docker is for production btw.

services:
  rtk-refresh-token-auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    env_file:
      - ./.env
    restart: unless-stopped
    command: ["/bin/sh", "-c", "pnpm run start"]
